# SPDX-FileCopyrightText: 2025 Logenium Authors and Contributors
# SPDX-License-Identifier: BSD-3-Clause

from dataclasses import dataclass
from pathlib import Path

@dataclass(frozen=True)
class CodegenFiles:
    xdg_shell_client_header: Path = ...
    xdg_shell_protocol_source: Path = ...
    xdg_decoration_client_header: Path = ...
    xdg_decoration_protocol_source: Path = ...
