# SPDX-FileCopyrightText: 2025 Logenium Authors and Contributors
# SPDX-License-Identifier: BSD-3-Clause

from dataclasses import dataclass
from pathlib import Path

@dataclass(frozen=True)
class Directories:
    root: Path = ...
    build: Path = ...
    libs: Path = ...
    cache: Path = ...
    vscode: Path = ...
    logenium_source: Path = ...
    logenium_include: Path = ...
    logenium_cmake: Path = ...
    logenium_tests: Path = ...
    xheader_root: Path = ...
    xheader_source: Path = ...
    xheader_include: Path = ...
    xheader_cmake: Path = ...
    xheader_tests: Path = ...
    debug_root: Path = ...
    debug_source: Path = ...
    debug_include: Path = ...
    debug_cmake: Path = ...
    debug_tests: Path = ...
    debug_docs: Path = ...
    devutils_root: Path = ...
    devutils_source: Path = ...
    devutils_cache: Path = ...
    corelib_root: Path = ...
    corelib_source: Path = ...
    corelib_include: Path = ...
    corelib_cmake: Path = ...
    corelib_tests: Path = ...
    corelib_docs: Path = ...
    logging_root: Path = ...
    logging_source: Path = ...
    logging_include: Path = ...
    logging_cmake: Path = ...
    logging_tests: Path = ...
    logging_docs: Path = ...

DOCS_DIRS: list[Path]
