# SPDX-FileCopyrightText: 2025 Logenium Authors and Contributors
# SPDX-License-Identifier: BSD-3-Clause

from dataclasses import dataclass
from pathlib import Path

@dataclass(frozen=True)
class Files:
    corelib_doxygen_config: Path = ...
    devutils_lint_cache_file: Path = ...
    devutils_license_headers_cache_file: Path = ...
    devutils_pyproject_toml: Path = ...
    debug_doxygen_config: Path = ...
    logging_doxygen_config: Path = ...
    ninja_build_file: Path = ...

DOXYGEN_CONFIGS: dict[str, Path]
