# SPDX-FileCopyrightText: 2025 Logenium Authors and Contributors
# SPDX-License-Identifier: BSD-3-Clause

import typer

from devutils.constants.paths import ConfigFiles as ConfigFiles
from devutils.constants.paths import Directories as Directories
from devutils.constants.paths import JsonSchemas as JsonSchemas

ConfigEntry = dict[str, str | list[str]]
WaylandConfig = dict[str, list[ConfigEntry]]
wayland: typer.Typer

def check_wayland_scanner_available() -> bool: ...
def validate_config_schema(config: WaylandConfig) -> None: ...
def evaluate_condition(condition: str) -> bool: ...
def substitute_variables(command: list[str], variables: dict[str, str]) -> list[str]: ...
def generate_file_from_config(file_path: str, config: list[ConfigEntry]) -> bool: ...
def main(ctx: typer.Context) -> None: ...
