#ifndef LOGENIUM_CORELIB_INTERNAL_TRACING_HXX
#define LOGENIUM_CORELIB_INTERNAL_TRACING_HXX

#include <debug/tracing.hxx>

#ifndef __LOGENIUM_CORELIB_ENABLE_TRACING__
#define __LOGENIUM_CORELIB_ENABLE_TRACING__ 0
#endif

#if __LOGENIUM_CORELIB_ENABLE_TRACING__

#define CRLB_ZONE_SCOPED ZoneScoped

#else

#define CRLB_ZONE_SCOPED

#endif

#endif  // LOGENIUM_CORELIB_INTERNAL_TRACING_HXX
