import pathlib
from dataclasses import dataclass

from _typeshed import Incomplete

from devutils.constants import Directories as Directories
from devutils.constants import Extensions as Extensions
from devutils.utils.file_checking import FileResult as FileResult
from devutils.utils.file_checking import FileStatus as FileStatus
from devutils.utils.file_checking import LanguageConfig as LanguageConfig
from devutils.utils.file_checking import Statistics as Statistics
from devutils.utils.file_checking import print_status as print_status

format: Incomplete

@dataclass
class FormatLanguageConfig(LanguageConfig):
    check_args: list[str]
    fix_args: list[str]
    formatter_tool: str = ...

def get_language_configs() -> list[FormatLanguageConfig]: ...
def check_tool_available(tool_name: str) -> bool: ...
def check_file_formatting(file_path: pathlib.Path, config: FormatLanguageConfig) -> FileResult: ...
def fix_file_formatting(file_path: pathlib.Path, config: FormatLanguageConfig) -> bool: ...
def check_files(files: list[pathlib.Path], config: FormatLanguageConfig, stats: Statistics) -> None: ...
def fix_files(files: list[pathlib.Path], config: FormatLanguageConfig, stats: Statistics) -> None: ...
def check() -> None: ...
def fix() -> None: ...
