import pathlib
from _typeshed import Incomplete
from dataclasses import dataclass
from devutils.constants import Directories as Directories, Extensions as Extensions
from devutils.utils.file_checking import (
    FileResult as FileResult,
    FileStatus as FileStatus,
    LanguageConfig as LanguageConfig,
    Statistics as Statistics,
    print_status as print_status,
)

format: Incomplete

@dataclass
class FormatLanguageConfig(LanguageConfig):
    check_args: list[str]
    fix_args: list[str]
    formatter_tool: str = ...

def get_language_configs() -> list[FormatLanguageConfig]: ...
def check_tool_available(tool_name: str) -> bool: ...
def check_file_formatting(file_path: pathlib.Path, config: FormatLanguageConfig) -> FileResult: ...
def fix_file_formatting(file_path: pathlib.Path, config: FormatLanguageConfig) -> bool: ...
def check_files(files: list[pathlib.Path], config: FormatLanguageConfig, stats: Statistics) -> None: ...
def fix_files(files: list[pathlib.Path], config: FormatLanguageConfig, stats: Statistics) -> None: ...
def check() -> None: ...
def fix() -> None: ...
