import pathlib
from _typeshed import Incomplete
from dataclasses import dataclass
from devutils.constants import Directories as Directories, Extensions as Extensions
from devutils.utils.file_checking import FileResult as FileResult, FileStatus as FileStatus, LanguageConfig as LanguageConfig, Statistics as Statistics, print_status as print_status

lint: Incomplete

@dataclass
class LintStep:
    tool_name: str
    check_args: list[str]
    fix_args: list[str]
    can_fix: bool = ...

@dataclass
class LintLanguageConfig(LanguageConfig):
    lint_steps: list[LintStep]

def get_language_configs() -> list[LintLanguageConfig]: ...
def check_tool_available(tool_name: str) -> bool: ...
def check_file_lint(file_path: pathlib.Path, lint_step: LintStep) -> FileResult: ...
def fix_file_lint(file_path: pathlib.Path, lint_step: LintStep) -> bool: ...
def check_files(files: list[pathlib.Path], config: LintLanguageConfig, stats: Statistics) -> None: ...
def fix_files(files: list[pathlib.Path], config: LintLanguageConfig, stats: Statistics) -> None: ...
def check() -> None: ...
def fix() -> None: ...
