from .file_result import FileResult as FileResult
from .file_status import FileStatus as FileStatus
from dataclasses import dataclass

@dataclass
class Statistics:
    total: int = ...
    ok: int = ...
    issues: int = ...
    errors: int = ...
    fixed: int = ...
    skipped: int = ...
    issue_label: str = ...
    def record_result(self, result: FileResult) -> None: ...
    def record_fix(self, fixed: bool) -> None: ...
    def print_summary(self, mode: str) -> None: ...
    def has_failures(self) -> bool: ...
