from dataclasses import dataclass

from .file_result import FileResult as FileResult
from .file_status import FileStatus as FileStatus

@dataclass
class Statistics:
    total: int = ...
    ok: int = ...
    warnings: int = ...
    issues: int = ...
    errors: int = ...
    fixed: int = ...
    skipped: int = ...
    issue_label: str = ...
    def __post_init__(self) -> None: ...
    def record_result(self, result: FileResult) -> None: ...
    def record_fix(self, fixed: bool) -> None: ...
    def print_summary(self, mode: str) -> None: ...
    def has_failures(self) -> bool: ...
    def record_result_threadsafe(self, result: FileResult) -> None: ...
    def increment_total_threadsafe(self) -> None: ...
    def increment_errors_threadsafe(self) -> None: ...
    def record_fix_threadsafe(self, fixed: bool) -> None: ...
