# SPDX-FileCopyrightText: 2025 Logenium Authors and Contributors
# SPDX-License-Identifier: BSD-3-Clause

import pathlib

def find_files_by_name(path: pathlib.Path, name: str) -> list[pathlib.Path]: ...
def find_files_by_extensions(path: pathlib.Path, extensions: list[str]) -> list[pathlib.Path]: ...
def get_files_recursively(path: pathlib.Path) -> list[pathlib.Path]: ...
