from _typeshed import Incomplete

from devutils.constants import Directories as Directories

stubgen: Incomplete

def check_stubgen_available() -> bool: ...
def generate(verbose: bool = ...) -> None: ...
def check(verbose: bool = ...) -> None: ...
