# SPDX-FileCopyrightText: 2025 Logenium Authors and Contributors
# SPDX-License-Identifier: BSD-3-Clause

from dataclasses import dataclass

from _typeshed import Incomplete

@dataclass(frozen=True)
class _Comments:
    c: str = ...
    cpp: str = ...
    python: str = ...
    cmake: str = ...
    powershell: str = ...
    bat: str = ...
    bash: str = ...

Comments: Incomplete
