from dataclasses import dataclass

from _typeshed import Incomplete

@dataclass(frozen=True)
class _Comments:
    c: str = ...
    cpp: str = ...
    python: str = ...
    cmake: str = ...
    powershell: str = ...
    bat: str = ...

Comments: Incomplete
