# SPDX-FileCopyrightText: 2025 Logenium Authors and Contributors
# SPDX-License-Identifier: BSD-3-Clause

from .comments import Comments as Comments

def generate_license_header(year: int, comment_style: str) -> list[str]: ...
def generate_c_header(year: int) -> list[str]: ...
def generate_cpp_header(year: int) -> list[str]: ...
def generate_python_header(year: int) -> list[str]: ...
def generate_cmake_header(year: int) -> list[str]: ...
def generate_powershell_header(year: int) -> list[str]: ...
def generate_bat_header(year: int) -> list[str]: ...
def generate_bash_header(year: int) -> list[str]: ...
