from dataclasses import dataclass
from pathlib import Path

from _typeshed import Incomplete

@dataclass(frozen=True)
class _Directories:
    root: Path = ...
    build: Path = ...
    libs: Path = ...
    logenium_source: Path = ...
    logenium_include: Path = ...
    logenium_cmake: Path = ...
    xheader_root: Path = ...
    xheader_source: Path = ...
    xheader_include: Path = ...
    xheader_cmake: Path = ...
    xheader_tests: Path = ...
    debug_root: Path = ...
    debug_source: Path = ...
    debug_include: Path = ...
    devutils_root: Path = ...
    devutils_source: Path = ...

@dataclass(frozen=True)
class _Files:
    ninja_build_file: Path = ...
    lint_cache_file: Path = ...

Directories: Incomplete
Files: Incomplete
